# Creating a Deployment with the type RollingUpdate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-pod-new
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: liveapp
  template:
    metadata:
      labels:
        app: liveapp
    spec:
      containers:
        - name: production-container
          image: aggrawalshanky/testimage
          ports:
            - containerPort: 80
---
# Creating a Service for the pod
apiVersion: v1
kind: Service
metadata:
  name: svcnew
spec:
  type: NodePort
  selector:
    app: liveapp
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30009
